parameters:
  - name: product_id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64
  - name: price_division
    in: path
    description: 価格区分
    required: true
    schema:
      type: integer
      format: int32
  - name: store_id
    in: path
    description: 店舗ID
    required: true
    schema:
      type: integer
      format: int64
  - name: start_date
    in: path
    description: 適用開始日(YYYY-MM-DD形式)
    required: true
    schema:
      type: string
      format: date

delete:
  summary: 商品価格情報の削除
  description: 指定した商品の特定価格区分、店舗、適用開始日の価格情報を削除します。
  operationId: deleteProductPrice
  tags:
    - 商品
  responses:
    '204':
      description: 商品価格情報の削除に成功
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品価格情報が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 削除できない状態（他のデータから参照されているなど）
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
