parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64
  - name: reservation_product_id
    in: path
    description: 引当商品ID
    required: true
    schema:
      type: integer
      format: int64

delete:
  summary: 商品の在庫引当情報削除
  description: 指定した商品IDと引当商品IDの在庫引当情報を削除します。
  operationId: deleteProductInventoryReservation
  tags:
    - 商品
  responses:
    '204':
      description: 商品の在庫引当情報の削除に成功
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品または在庫引当情報が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 削除できない状態（他のデータから参照されているなど）
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
