parameters:
  - name: product_id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64
  - name: no
    in: path
    description: 予約項目番号
    required: true
    schema:
      type: integer
      format: int32

delete:
  summary: 商品の予約項目削除
  description: 指定した商品IDと予約項目番号の予約項目情報を削除します。
  operationId: deleteProductReserveItem
  tags:
    - 商品
  responses:
    '204':
      description: 商品予約項目の削除に成功
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品または予約項目が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 削除できない状態（他のデータから参照されているなど）
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
