parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64

get:
  summary: 商品の予約項目取得
  description: 指定した商品IDの予約項目情報を取得します。
  operationId: getProductReserveItems
  tags:
    - 商品
  parameters:
    - name: limit
      in: query
      description: 取得件数
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        default: 100
    - name: page
      in: query
      description: ページ番号
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1
    - name: sort
      in: query
      description: ソート順
      schema:
        type: string
        enum:
          - no
    - name: fields
      in: query
      description: 取得するフィールド
      schema:
        type: array
        items:
          type: string
        default: ["*"]
  responses:
    '200':
      description: 商品の予約項目情報を返却
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '../../schemas/products/ProductReserveItem.yaml'
              total:
                type: integer
                description: 総件数
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:read
    - UserAccessToken:
        - pos.products:read

