parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64

put:
  summary: 商品アイコン画像の更新
  description: 指定した商品IDのアイコン画像を更新します。
  operationId: updateProductIconImage
  tags:
    - 商品
  requestBody:
    required: true
    content:
      multipart/form-data:
        schema:
          type: object
          properties:
            image:
              type: string
              format: binary
              description: 画像ファイル（JPEG、PNG形式）
  responses:
    '200':
      description: 商品アイコン画像の更新に成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/products/ProductImage.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '413':
      description: ファイルサイズが上限を超えている
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '415':
      description: サポートされていないファイル形式
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write

delete:
  summary: 商品アイコン画像の削除
  description: 指定した商品IDのアイコン画像を削除します。
  operationId: deleteProductIconImage
  tags:
    - 商品
  responses:
    '204':
      description: 商品アイコン画像の削除に成功
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品またはアイコン画像が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
