parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64

get:
  summary: 商品の取得
  description: 指定したIDの商品情報を取得します。
  operationId: getProduct
  tags:
    - 商品
  parameters:
    - name: fields
      in: query
      description: 取得するフィールド
      schema:
        type: array
        items:
          type: string
        default: ["*"]
  responses:
    '200':
      description: 商品情報を返却
      content:
        application/json:
          schema:
            $ref: '../../schemas/products/Product.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:read
    - UserAccessToken:
        - pos.products:read

put:
  summary: 商品の更新
  description: 指定したIDの商品情報を更新します。
  operationId: updateProduct
  tags:
    - 商品
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/products/ProductUpdate.yaml'
  responses:
    '200':
      description: 商品の更新に成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/products/Product.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 既存データとの競合エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write

delete:
  summary: 商品の削除
  description: 指定したIDの商品を論理削除します。
  operationId: deleteProduct
  tags:
    - 商品
  responses:
    '204':
      description: 商品の削除に成功
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 削除できない状態（関連データが存在するなど）
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
