get:
  summary: 商品一覧の取得
  description: |
    商品の一覧を取得します。
    検索条件を指定することで、特定の商品のみを取得することも可能です。
  operationId: getProducts
  tags:
    - 商品
  parameters:
    - name: limit
      in: query
      description: 取得件数
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        default: 100
    - name: page
      in: query
      description: ページ番号
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1
    - name: sort
      in: query
      description: ソート順
      schema:
        type: string
        enum:
          - productId
          - productCode
          - productName
          - categoryId
          - supplierName
          - price
          - cost
          - modified
        default: productId
    - name: product_id
      in: query
      description: 商品ID
      schema:
        type: integer
        format: int64
    - name: product_code
      in: query
      description: 商品コード
      schema:
        type: string
    - name: group_code
      in: query
      description: グループコード
      schema:
        type: string
    - name: category_id
      in: query
      description: 部門ID
      schema:
        type: integer
        format: int64
    - name: display_flag
      in: query
      description: 端末表示（0. 表示しない、1. 表示する）
      schema:
        type: string
        enum: ['0', '1']
    - name: division
      in: query
      description: 商品区分 (0：通常商品、1：回数券、2：オプション商品)
      schema:
        type: string
        enum: ['0', '1', '2']
    - name: sales_division
      in: query
      description: 売上区分 (0:売上対象、1:売上対象外)
      schema:
        type: string
        enum: ['0', '1']
    - name: stock_control_division
      in: query
      description: 在庫管理区分 (0:在庫管理対象、1:在庫管理対象外)
      schema:
        type: string
        enum: ['0', '1']
    - name: supplier_product_no
      in: query
      description: 品番
      schema:
        type: string
    - name: upd_date_time-from
      in: query
      description: |
        更新日時(From)：登録時・更新時の日時。[YYYY-MM-DDThh:mm:ssTZD]
        ※ From〜Toの期間は最大31日までの指定でご利用ください
      schema:
        type: string
        format: date-time
    - name: upd_date_time-to
      in: query
      description: |
        更新日時(To)：登録時・更新時の日時。[YYYY-MM-DDThh:mm:ssTZD]
        ※ From〜Toの期間は最大31日までの指定でご利用ください
      schema:
        type: string
        format: date-time
    - name: fields
      in: query
      description: 取得するフィールド
      schema:
        type: array
        items:
          type: string
  responses:
    '200':
      description: 商品一覧を返却
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '../../schemas/products/Product.yaml'
              total:
                type: integer
                description: 総件数
              limit:
                type: integer
                description: 取得件数
              page:
                type: integer
                description: ページ番号
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:read
    - UserAccessToken:
        - pos.products:read

post:
  summary: 商品の新規登録
  description: 商品を新規登録します。
  operationId: createProduct
  tags:
    - 商品
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/products/ProductCreate.yaml'
  responses:
    '201':
      description: 商品の登録に成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/products/Product.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 既存データとの競合エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
