parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64

get:
  summary: 商品の店舗関連情報取得
  description: 指定した商品IDの店舗関連情報を取得します。
  operationId: getProductStores
  tags:
    - 商品
  parameters:
    - name: store_id
      in: query
      description: 店舗ID
      schema:
        type: integer
        format: int64
    - name: fields
      in: query
      description: 取得するフィールド
      schema:
        type: array
        items:
          type: string
        default: ["*"]
  responses:
    '200':
      description: 商品の店舗関連情報を返却
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '../../schemas/products/ProductStore.yaml'
              total:
                type: integer
                description: 総件数
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:read
    - UserAccessToken:
        - pos.products:read

post:
  summary: 商品の店舗関連情報登録
  description: 指定した商品IDに店舗関連情報を登録します。
  operationId: createProductStore
  tags:
    - 商品
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/products/ProductStore.yaml'
  responses:
    '201':
      description: 商品の店舗関連情報の登録に成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/products/ProductStore.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品または店舗が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 既存データとの競合エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write

put:
  summary: 商品の店舗関連情報一括更新
  description: 指定した商品IDの店舗関連情報を一括で更新します。
  operationId: updateProductStores
  tags:
    - 商品
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '../../schemas/products/ProductStore.yaml'
  responses:
    '200':
      description: 商品の店舗関連情報の更新に成功
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '../../schemas/products/ProductStore.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 既存データとの競合エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
