parameters:
  - name: id
    in: path
    description: 商品ID
    required: true
    schema:
      type: integer
      format: int64

get:
  summary: 商品の在庫引当情報取得
  description: 指定した商品IDの在庫引当情報を取得します。
  operationId: getProductInventoryReservations
  tags:
    - 商品
  parameters:
    - name: fields
      in: query
      description: 取得するフィールド
      schema:
        type: array
        items:
          type: string
        default: ["*"]
  responses:
    '200':
      description: 商品の在庫引当情報を返却
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '../../schemas/products/ProductInventoryReservation.yaml'
              total:
                type: integer
                description: 総件数
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:read
    - UserAccessToken:
        - pos.products:read

post:
  summary: 商品の在庫引当情報登録
  description: 指定した商品IDに在庫引当情報を登録します。
  operationId: createProductInventoryReservation
  tags:
    - 商品
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/products/ProductInventoryReservation.yaml'
  responses:
    '201':
      description: 商品の在庫引当情報の登録に成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/products/ProductInventoryReservation.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品または引当先商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 既存データとの競合エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write

put:
  summary: 商品の在庫引当情報一括更新
  description: 指定した商品IDの在庫引当情報を一括で更新します。
  operationId: updateProductInventoryReservations
  tags:
    - 商品
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '../../schemas/products/ProductInventoryReservation.yaml'
  responses:
    '200':
      description: 商品の在庫引当情報の更新に成功
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '../../schemas/products/ProductInventoryReservation.yaml'
    '400':
      description: リクエストパラメータが不正
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '401':
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '403':
      description: 権限エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 商品が存在しない
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '409':
      description: 既存データとの競合エラー
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
  security:
    - AppAccessToken:
        - pos.products:write
    - UserAccessToken:
        - pos.products:write
