get:
  summary: オプショングループ一覧取得
  description: |
    オプショングループの一覧を取得します。
    
    Plans:
    スタンダード・プレミアム・プレミアムプラス・フードビジネス・リテールビジネス
    
    sortで使用可能なパラメータ
    - productOptionGroupId：商品オプショングループID
    - conditionId：条件ID
    - updDateTime：更新日時
  tags:
    - オプショングループ
  security:
    - AppAccessToken: [pos.products:read]
    - UserAccessToken: [pos.products:read]
  parameters:
    - name: contract_id
      in: path
      required: true
      schema:
        type: string
      description: 契約ID
    - name: fields
      in: query
      schema:
        type: array
        items:
          type: string
      description: |
        検索パラメータ（カンマ区切りで指定可）
        Response項目を指定可能
        ※一部項目(withで指定する項目、2階層目以降の項目)については指定不可
    - name: sort
      in: query
      schema:
        type: string
      description: |
        並び順（カンマ区切りで指定可）
        指定可能な項目については上記参照
    - name: limit
      in: query
      schema:
        type: integer
      description: 上限数
    - name: page
      in: query
      schema:
        type: integer
      description: ページ
    - name: product_option_group_name
      in: query
      schema:
        type: string
      description: オプショングループ名
    - name: condition_id
      in: query
      schema:
        type: string
      description: 条件ID (0:条件なし、1:全体、2:部門毎)
  responses:
    '200':
      description: 取得成功
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/options/ProductOptionGroup.yaml'

post:
  summary: オプショングループ登録
  description: |
    オプショングループを登録します。
    
    Plans:
    スタンダード・プレミアム・プレミアムプラス・フードビジネス・リテールビジネス
  tags:
    - オプショングループ
  security:
    - AppAccessToken: [pos.products:write]
    - UserAccessToken: [pos.products:write]
  parameters:
    - name: contract_id
      in: path
      required: true
      schema:
        type: string
      description: 契約ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/options/ProductOptionGroupCreate.yaml'
  responses:
    '200':
      description: 更新成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/options/ProductOptionGroup.yaml'
    '400':
      description: 入力チェックエラーの場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'