get:
  summary: オプショングループ取得
  description: |
    指定されたオプショングループを取得します。
    
    Plans:
    スタンダード・プレミアム・プレミアムプラス・フードビジネス・リテールビジネス
  tags:
    - オプショングループ
  security:
    - AppAccessToken: [pos.products:read]
    - UserAccessToken: [pos.products:read]
  parameters:
    - name: contract_id
      in: path
      required: true
      schema:
        type: string
      description: 契約ID
    - name: id
      in: path
      required: true
      schema:
        type: string
      description: オプショングループID
    - name: fields
      in: query
      schema:
        type: array
        items:
          type: string
      description: |
        検索パラメータ（カンマ区切りで指定可）
        Response項目を指定可能
        ※一部項目(withで指定する項目、2階層目以降の項目)については指定不可
    - name: with_products
      in: query
      schema:
        type: string
        enum: ["all", "none"]
        default: "none"
      description: オプショングループ商品情報を付加するか(付加する場合はall, しない場合はnone)
  responses:
    '200':
      description: 取得成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/options/ProductOptionGroup.yaml'
    '404':
      description: 指定されたIDが存在しない場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'

patch:
  summary: オプショングループ更新
  description: |
    オプショングループを更新します。
    
    Plans:
    スタンダード・プレミアム・プレミアムプラス・フードビジネス・リテールビジネス
  tags:
    - オプショングループ
  security:
    - AppAccessToken: [pos.products:write]
    - UserAccessToken: [pos.products:write]
  parameters:
    - name: contract_id
      in: path
      required: true
      schema:
        type: string
      description: 契約ID
    - name: id
      in: path
      required: true
      schema:
        type: string
      description: オプショングループID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/options/ProductOptionGroupUpdate.yaml'
  responses:
    '200':
      description: 更新成功
      content:
        application/json:
          schema:
            $ref: '../../schemas/options/ProductOptionGroup.yaml'
    '400':
      description: 入力チェックエラーの場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 指定されたIDが存在しない場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'

delete:
  summary: オプショングループ削除
  description: |
    オプショングループを削除します。
    
    Plans:
    スタンダード・プレミアム・プレミアムプラス・フードビジネス・リテールビジネス
  tags:
    - オプショングループ
  security:
    - AppAccessToken: [pos.products:write]
    - UserAccessToken: [pos.products:write]
  parameters:
    - name: contract_id
      in: path
      required: true
      schema:
        type: string
      description: 契約ID
    - name: id
      in: path
      required: true
      schema:
        type: string
      description: オプショングループID
  responses:
    '200':
      description: 削除成功
    '400':
      description: 指定されたオプショングループが使用中の場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: 指定されたIDが存在しない場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'