delete:
  summary: オプショングループ商品削除
  description: |
    指定されたオプショングループ商品を削除します。
    
    Plans:
    スタンダード・プレミアム・プレミアムプラス・フードビジネス・リテールビジネス
  tags:
    - オプショングループ
  security:
    - AppAccessToken: [pos.products:write]
    - UserAccessToken: [pos.products:write]
  parameters:
    - name: contract_id
      in: path
      required: true
      schema:
        type: string
      description: 契約ID
    - name: id
      in: path
      required: true
      schema:
        type: string
      description: オプショングループID
    - name: product_id
      in: path
      required: true
      schema:
        type: string
      description: 商品ID
  responses:
    '200':
      description: 削除成功
    '400':
      description: 指定されたオプショングループのオプション商品が１件の場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'
    '404':
      description: |
        URIで指定されたオプショングループが存在しない場合
        URIで指定された商品が存在しない場合
        URIで指定されたパラメータの組み合わせが存在しない場合
      content:
        application/json:
          schema:
            $ref: '../../schemas/common/Error.yaml'