type: object
description: オプショングループ登録情報
properties:
  productOptionGroupName:
    type: string
    description: オプショングループ名
    maxLength: 85
    example: "トッピング"
  conditionId:
    type: string
    description: 条件ID (0:条件なし、1:全体、2:部門毎)
    enum: ["0", "1", "2"]
    example: "1"
  max:
    type: string
    description: 適用条件の上限
    example: "3"
  min:
    type: string
    description: 適用条件の下限
    example: "1"
  products:
    type: array
    description: オプショングループ商品
    items:
      type: object
      required:
        - productId
      properties:
        productId:
          type: string
          description: 商品ID
          example: "12345"
required:
  - productOptionGroupName
  - conditionId
  - products