type: object
description: 商品属性項目情報
properties:
  code:
    type: string
    description: 属性項目コード
    example: "CODE01"
  attributeNo:
    type: string
    description: 属性番号
    example: "1"
  attributeItemName:
    type: string
    description: 属性項目名称
    example: "ブラック"
  displaySequence:
    type: string
    description: 表示順序
    example: "1"
  status:
    type: string
    description: ステータス (0:無効、1:有効)
    enum: ["0", "1"]
    default: "1"
    example: "1"
  insDateTime:
    type: string
    format: date-time
    description: 登録日時
    example: "2023-01-01T00:00:00+09:00"
  updDateTime:
    type: string
    format: date-time
    description: 更新日時
    example: "2023-01-01T00:00:00+09:00"
required:
  - attributeNo
  - attributeItemName
